# This is a basic workflow to help you get started with Actions

name: Generate HTML

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get -y update && sudo apt-get install chromium-browser 

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install dependencies
        run: npm install

      - name: Make Run
        run: make run
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: output.html
          path: output/output.html
          if-no-files-found: error
